### ISSUE TITLE
`$1/35$`未被渲染

### ISSUE THREAD

**Issue by YDX-2147483647** [csimide/cuti-docs#1]
[此处](https://csimide.github.io/cuti-docs/zh-CN/fakebold.html)`$1/35$`未被渲染为 $1/35$。

![图片](https://github.com/user-attachments/assets/47125894-332d-46ac-83cc-01f19534b5d2)

https://github.com/csimide/cuti-docs/blob/feeee58ca3c7f6cb49cabd4dcab138354e3c436c/docs/zh-CN/fakebold.md?plain=1#L10

相关文档：[Markdown Extensions | VitePress](https://vitepress.dev/guide/markdown#math-equations)

不过若公式不多，建议直接换成`1/35`。

**Comment by csimide** [comment]
已在 https://github.com/csimide/cuti-docs/commit/e7e095782af1e32d4ce7ae37b31a2d9ecdb09769 中修复。

之前从 typst 文稿迁移的时候忘记处理了，现已改为纯文本（不再使用公式）。

谢谢
